### ISSUE TITLE
Cannot find store for device: undefined

### ISSUE THREAD

**Issue by ScriptingSloth** [ObjectIsAdvantag/roomkit-collector#5] opened 2018-07-09 19:58 UTC
Upon running DEBUG=collector*,api*  WINDOW=60   node server.js,  Terminal returns 

```
searching store for device: undefined +39ms
  collector:fine could not find store for device: undefined +0ms
```

**Comment by ObjectIsAdvantag** [comment] 2020-01-23 03:59
wow, this was opened long ago

I could not reproduce this error, today
I suspect the API path is not correct and does not map to a device, though, I could not get an 'undefined' log by trying a few incorrect path.

closing

please reopen if you still want to investigate your issue. To do so, I would need your devices.json file (please remove credentials), your console logs, and the API path you're requesting.

**Closed by ObjectIsAdvantag** 2020-01-23 03:59 UTC
